= Anypoint Platform Hosting Options

MuleSoft provides and supports different hosting options to accomadate different data security, data privacy, and legal requirements. These options enable you to control the physical location where your and your customer's data are hosted. This includes

* Your assets, including API specifications and Mule applications
* Metadata about your assets
* Data that passes through your APIs and Mule applications.

This data remains within the physical location required by your companies IT policies and requirements. For example, MuleSoft provides an EU Cloud which enables you to maintain all of your data on your own data centers or within the European Union.

== Control Plane and Runtime Plane

To understand the different possible hosting options, it is important to understand the following concepts:

image::intro-control-vs-runtime-planes.bnp[]

* Control plane
+
The control plane contains the Anypoint Platform components for designing, deploying, and managing APIs and Mule applications.

* Runtime plane
+
The runtime plane contains the runtime components of Anypoint Platform, including the Mule runtime server and other services.

== MuleSoft Managed Hosting Options

The following diagram shows the possible hosting options where MuleSoft hosts and manages both the control plane and runtime plane:

image::intro-cloud-hosting-options.bmp[]

* US Cloud
+
In the US Cloud, Anypoint Platform and CloudHub are physically hosted within the United States. To improve performance and reduce latency, you can deploy APIs and Mule applications to Mule Runtimes located in different regions. When enabled, each regions appears as different deployment targets during deployment. This is the default environment.

* EU Cloud
+
In the EU Cloud, Anypoint Platform and CloudHub are physically hosted within the European Union.
+
[NOTE]
Anypoint Partner Manager is not supported in the EU Cloud.

* MuleSoft Government Cloud
+
MuleSoft Government Cloud is a secure, FedRAMP-compliant deployment environment that enables government agencies to use Anypoint Platform in the cloud.
+
See xref:gov-cloud::index.adoc[About Government Cloud]

=== Support Matrix for Cloud Hosting Options

Not all Anypoint Platform components are supported in all cloud environments. The following table shows which component is supported by each environment:

[%header,cols="4*a"]
|===
| Anypoint Platform Component | US Cloud | EU Cloud | MuleSoft Government Cloud
| API Designer | Y | Y | Y
| Anypoint Studio | Y | Y | Y
| Flow Designer | Y | Y | N
| Anypoint Exchange | Y | Y | Y
| Anypoint API Community Manager* | Y | Y | N
| Anypoint Partner Manager | Y | N | N
| Access management | Y | Y | Y
| Analytics | Y | Y | N
| Anypoint API Manager | Y | Y | Y
| Anypoint Runtime Manager | Y | Y | Y
| Anypoint Monitoring | Y | Y | N
| Secrets manager | Y | Y | N
| Anypoint Visualizer | Y | Y | N
| Anypoint Security edge policies | Y | Y | N
| Anypoint Security tokenization | Y | Y | N
|===

[NOTE]
Anypoint API Community Manager (API Community Manager) incorporates capabilities and functionality of the Salesforce platform into Anypoint Platform.

== Hybrid Hosting Options

image::intro-hybrid-hosting-options.bmp[]

=== Support Matrix for Hybrid Hosting Options

Not all Anypoint Platform components are supported in each of these Mule runtime server hosting options:

[%header,cols="4*a"]
|===
| Anypoint Platform Component | CloudHub | Runtime Fabric | Hybrid
| Mule runtime engine | Y | Y | Y
| Anypoint MQ | Y | N | N
| Anypoint Object Store | Y | N | Y
| Connectors | Y | Y | Y
|===

== Anypoint Platform Private Cloud Edition

image:intro-private-cloud-edition.bmp[]

=== Support Matrix for Anypoint Private Cloud Edition

The following table lists the Anypoint Platform components supported by each version:

[%header,cols="3*a"]
|===
| Anypoint Platform Component | Anypoint Platform | Anypoint Platform PCE
| API Designer | Y | Y
| Anypoint Studio | Y | Y
| Flow Designer | Y | N
| Anypoint Exchange | Y | Y
| Anypoint API Community Manager* | Y | N
| Anypoint Partner Manager | Y | N
| Access management | Y | Y
| Analytics | Y | N
| Anypoint API Manager | Y | Y
| Anypoint Runtime Manager | Y | Y (Insight not supported)
| Anypoint Monitoring | Y | N
| Secrets manager | Y | N
| Anypoint Visualizer | Y | N
| Anypoint Security edge policies | Y | N
| Anypoint Security tokenization | Y | N
|===

[NOTE]
Anypoint API Community Manager (API Community Manager) incorporates capabilities and functionality of the Salesforce platform into Anypoint Platform.
