= Anypoint Platform Hosting Options

MuleSoft provides different product hosting options to accomadate different data security, data privacy, and legal requirements.

Gives you control over the physical location where your and your customer's data are hosted. This includes customer data that passes through your APIs and Mule applications.

The data associated with each API and Mule application remains within the location required by your companies IT policies and requirements. For example, MuleSoft enables you to maintain one-hundred percent of your data on your own data centers or within the European Union.

== Hosting Options for Mule Runtime Server

Gives you control over the physical location where your APIs and Mule applications are hosted.
The data associated with each API and Mule application remains within the location. The following system overview diagram shows the different hosting options of a Mule Runtime Server:


In this scenario, MuleSoft hosts Anypoint Exchange, Design Center, and Management Center (including API Manager and Runtime Manager). Different hosting options for the Mule Runtime server are:

* CloudHub (1)
+
CloudHub is a cloud-based environment that hosts instances of the Mule Runtime server for you. When you deploy an API or a Mule application to CloudHub, MuleSoft maintains high availablity and fail-over. MuleSoft is also responsible for clustering, failover, and load balancing.
+
MuleSoft provides different cloud hosting options depending to accomodate your data and regulator requirements. See [Hosting Options for Design Center and Management Center]

* Hybrid (2)
+
A hybrid environment is an environment where you host APIs and Mule applications to your data center, but MuleSoft hosts the Design Center and Management Center components in the cloud. This scenario enables you to host Mule Runtime server in an environment that you manage. All customer data that passes through your API or Mule application remains in this environment.
+
Within a hybrid environment, you are responsible for providing the infrastructure where the Mule Runtime Server is hosted. In a Hybrid environment, the Mule Runtime Server can run on a physical server, a virtual machine, or within a 3rd-party cloud installation like Amazon Web Services or Microsoft Azure.
+
In this environment, you are responsible for the framework that provides high-availability, failover, clustering and load balancing.

* Runtime Fabric (3)
+
Runtim Fabric enables your to host Mule Runtime server within a data center that you control and manage. Enables your to host Mule Runtime server within a data center that you control and manage. Also, like a hybrid installation, Runtime Fabric supports hosting Mule Runtime Servers in a physical server, a virtual machine or within AWS/Azure. However, RTF is a network appliance that uses Kubernetes to manage HA, failover, clustering, and load balancing.

Not all Anypoint Platform components are supported in each of these hosting options as shown in the following table:

[%header,cols="4*a"]
|===
| Anypoint Platform Component | CloudHub | Runtime Fabric | Hybrid
| Mule runtime engine | Y | Y | Y
| Anypoint MQ | Y | N | N
| Anypoint Object Store | Y | N | Y
| Connectors | Y | Y | Y
|===

== Hosting Options for Exchange, Design Center, Management Center

MuleSoft provides different hosting options for Exchange, Design Center, and Management Center.

* Anypoint Platform
+

* Anypoint Platform Private Cloud Edition (PCE)
+
- Supports deploying to CloudHub.
	- Enables you to control the environment where your assets stored
	- Enables you to control where your application metadata is stored

- Supports deploying to Hybrid runtime environments
	- This enables you to host 100% of APP functionality within your own data center.

[NOTE]
Anypoint Platform Private Cloud Edition does not support deploying APIs and Mule applications to Anypoint Runtime Fabric.

The following table lists the Anypoint Platform components supported by each version:

[%header,cols="3*a"]
|===
| Anypoint Platform Component | Anypoint Platform | Anypoint Platform PCE
| API Designer | Y | Y
| Anypoint Studio | Y | Y
| Flow Designer | Y | N
| Anypoint Exchange | Y | Y
| Anypoint API Community Manager* | Y | N
| Anypoint Partner Manager | Y | N
| Access management | Y | Y
| Analytics | Y | N
| Anypoint API Manager | Y | Y
| Anypoint Runtime Manager | Y | Y (Insight not supported)
| Anypoint Monitoring | Y | N
| Secrets manager | Y | N
| Anypoint Visualizer | Y | N
| Anypoint Security edge policies | Y | N
| Anypoint Security tokenization | Y | N
|===

[NOTE]
Anypoint API Community Manager (API Community Manager) incorporates capabilities and functionality of the Salesforce platform into Anypoint Platform.

== Cloud Hosting Option

Hosting Options Based on Data Security and Compliance Requirements

To enable data security and compliance MuleSoft provides different cloud environments.

* US Cloud
+
In this environment, Design Center, Management Center and CloudHub are physically hosted within the United States. To improve performance and reduce latency, you can deploy APIs and Mule applications to Mule Runtimes located in different regions. When enabled, each regions appears as different deployment targets during deployment. This is the default environment.

* EU Cloud
+
Both Design Center/Management Center and CloudHub are physically hosted within the European Union. Anypoint Partner Manager is not supported in the EU Cloud.

* MuleSoft Government Cloud
+
a secure, FedRAMP-compliant deployment environment that enables government agencies to use Anypoint Platform in the cloud.

Not all Anypoint Platform components are supported in all cloud hosting options. The following table shows which component is supported by each option:

[%header,cols="4*a"]
|===
| Anypoint Platform Component | US Cloud | EU Cloud | MuleSoft Government Cloud
| API Designer | Y | Y | Y
| Anypoint Studio | Y | Y | Y
| Flow Designer | Y | Y | N
| Anypoint Exchange | Y | Y | Y
| Anypoint API Community Manager* | Y | Y | N
| Anypoint Partner Manager | Y | N | N
| Access management | Y | Y | Y
| Analytics | Y | Y | N
| Anypoint API Manager | Y | Y | Y
| Anypoint Runtime Manager | Y | Y | Y
| Anypoint Monitoring | Y | Y | N
| Secrets manager | Y | Y | N
| Anypoint Visualizer | Y | Y | N
| Anypoint Security edge policies | Y | Y | N
| Anypoint Security tokenization | Y | Y | N
|===

[NOTE]
Anypoint API Community Manager (API Community Manager) incorporates capabilities and functionality of the Salesforce platform into Anypoint Platform.

== See Also

* TBD
